[project]
name = "mini-sdp"
version = "1.0.0"
description = "(Mini-)SDP for SKAO technical assessment"
authors = [
    { name = "SimonP2207", email = "simonp2207@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "pydantic>=2.13.5",
]

[project.scripts]
mini-sdp = "mini_sdp:main"

[build-system]
requires = ["uv_build>=0.12.9,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "pytest-asyncio>=1.4.0",
    "ruff>=0.16.8",
]

[tool.pytest.ini_options]
testpaths = ["src/mini_sdp/tests"]
asyncio_mode = "auto"

[tool.ruff]
extend-exclude = ["docs/lib"]